# Generated by Django 5.2.10 on 2026-01-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdcount',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
